Calendar base
t3uyo3hi/multi-calendar-app pull request #12
Opened 2024-06-08 03:31 UTC by t3uyo3hi

###概要
CalendarHeaderとCalendarBaseの統合

2024-06-08 04:00 UTC, naoyuki2 requested changes
@t3uyo3hi 

確認お願いします！

2024-06-08 04:00 UTC, naoyuki2 commented on frontend/src/components/CalendarHeader.tsx
> +  ];
@t3uyo3hi 

ここは、毎回同じ値なのでCalendarHeaderの中に入れる必要はなさそうですね👀

monthsは9行目とかのinterfaceの下に書いた方が良さそう

2024-06-08 04:00 UTC, naoyuki2 commented on frontend/src/components/CalendarBody.tsx
>  };
@t3uyo3hi 

ここは、DayOfWeekHead.tsxっていうファイルに切り出した方が良さそうですね👀

CalendarBody.tsxっていうファイルならCalendarBodyコンポーネントだけ用意したい気持ちが

2024-06-08 04:00 UTC, naoyuki2 commented on frontend/src/css/style.css
@t3uyo3hi 

スタイリングは、Bootstrapと生のCSSどちらも使用する感じですか？👀
できることなら、全てBootstrapでやりたいかもです

2024-06-08 04:07 UTC, t3uyo3hi commented on frontend/src/components/CalendarHeader.tsx
> +  ];
CalendarHeader内から出す了解しました！
変更します！

2024-06-08 04:14 UTC, t3uyo3hi commented on frontend/src/components/CalendarBody.tsx
>  };
ありがとうございます！
DayOfWeekHead.tsx切り出してみます！

2024-06-08 04:23 UTC, t3uyo3hi commented on frontend/src/css/style.css
あんまり使い慣れてなくてCSSに頼ってしまいました。
カラーなどもあるので完全にできるかは分からないですが、極力Bootstrapだけで作れるように頑張ってみますね！

2024-06-09 00:10 UTC, naoyuki2 commented on frontend/src/css/style.css
@t3uyo3hi 

確かに細かいところは生のCSS使う方針で行きましょうか

2024-06-09 00:11 UTC, naoyuki2 approved these changes
LGTM🎉

2024-06-09 00:11 UTC, merged